version: '2'
services:
  userservice:
    image: danielbc/userservice
    ports:
      - "8080:8080"
    depends_on:
      - servicepostgres
  servicepostgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ccproject
      - POSTGRES_USER=Springboot
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./data/postgres:/var/lib/postgresql/data