
Vagrant.configure('2') do |config|

  config.vm.box = 'azure'
  config.ssh.private_key_path = '~/.ssh/id_rsa'

  config.vm.define 'database' do |database|
      
      database.vm.provider :azure do |azure, override|

          azure.tenant_id = ENV['AZURE_TENANT_ID']
          azure.client_id = ENV['AZURE_CLIENT_ID']
          azure.client_secret = ENV['AZURE_CLIENT_SECRET']
          azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']  
        
          azure.resource_group_name = 'CChito5' 
          azure.vm_image_urn = 'Canonical:UbuntuServer:18.04-LTS:latest'          
          azure.vm_name = 'posgresql'
          azure.vm_size = 'Basic_A0'
          azure.location = 'francecentral'
          azure.admin_username = 'daniel' 
          azure.tcp_endpoints = [22, 80, 5432]
      end 
    
      database.vm.provision 'ansible' do |ansible|
            ansible.playbook = 'provision_bd.yml'
      end
  end

  config.vm.define 'servicio' do |servicio|

      servicio.vm.provider :azure do |azure, override|

            azure.tenant_id = ENV['AZURE_TENANT_ID']
            azure.client_id = ENV['AZURE_CLIENT_ID']
            azure.client_secret = ENV['AZURE_CLIENT_SECRET']
            azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']     
            
            azure.resource_group_name = 'CChito5'
            azure.vm_size = 'Basic_A0'
            azure.vm_image_urn = 'Canonical:UbuntuServer:18.04-LTS:latest'      
            azure.vm_name = 'serviciousuarios'
            azure.location = 'francecentral'
            azure.admin_username = 'daniel'  
            azure.tcp_endpoints=[22, 80]
      end
        
      servicio.vm.provision 'ansible' do |ansible|
          ansible.playbook = 'provision.yml'
      end
  end

end
